export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";

export const FETCH_RECIPES = "FETCH_RECIPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
